Add bookings
catarena-s/java-shareit pull request #2
Opened 2023-05-03 14:36 UTC by catarena-s

2023-05-04 12:11 UTC, z8q requested changes

2023-05-04 12:11 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          if (!existUser(userId)) {
Тут происходит вызов метода, помеченного `@Transactional`, внутри класса.
По ссылке, в первом пункте описывается проблема
https://medium.com/javarevisited/spring-transactional-mistakes-everyone-did-31418e5a6d6b

Тут описывается похожая ситуация:
https://stackoverflow.com/questions/29230337/what-happens-if-one-transactional-annotated-method-is-calling-another-transact

Допускаю, что ты все это знаешь, и тут вызов такого вида не критичен)
Просто отмечу, что `@Transactional` над delete применится, а `@Transactional(readOnly = true)` уже не будет учитываться
Будет, как описано тут:
https://stackoverflow.com/questions/6222600/transactional-method-calling-another-method-without-transactional-anotation

Стоит проверить такие случаи в других классах

2023-05-04 12:11 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public UserDto create(
При попытке добавления дубля:
POST http://localhost:8080/users
{
	"name": "Bob",
	"email": "bob@yandex.ru"
}
Происходит InternalServerError и приходит ошибка:
An unexpected error has occurred: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

Не очень хорошо

2023-05-04 12:11 UTC, z8q commented on src/main/java/ru/practicum/shareit/util/QPredicate.java
> +    private List<Predicate> predicates = new ArrayList<>();
final

2023-05-04 19:17 UTC, catarena-s commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          if (!existUser(userId)) {
Спасибо, действительно упустила этот момент.
Пересмотрела код, пришла к выводу: в данном конкретном случае аннотация @Transaction у метода existUser не нужна. Поскольку он вызывается в других методах внутри транзакций.

2023-05-04 19:17 UTC, catarena-s commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public UserDto create(
Поправила

2023-05-04 19:17 UTC, catarena-s commented on src/main/java/ru/practicum/shareit/util/QPredicate.java
> +    private List<Predicate> predicates = new ArrayList<>();
Поправила

2023-05-05 19:46 UTC, z8q requested changes

2023-05-05 19:46 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingDto create(
Допускается бронирование одним пользователем одной вещи несколько раз на пересекающиеся диапазоны времени.
Плюс еще допускается забронировать и аппрувнуть ту же вещь вторым пользователем на пересекающийся диапазон.

В общем допускается бронь забронированных item-ов

2023-05-05 19:46 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public CommentDto createCommentToItem(@RequestHeader(value = "X-Sharer-User-Id", required = false) long userId,
Допускается оставить несколько комментариев одним пользователем на один item.

2023-05-05 19:46 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingDto approve(
Еще интересный момент.
Можно поставить аппрув на бронирование, время которого уже прошло.
В тз про это не сказано. Но при желании можно подумать)

2023-05-06 17:58 UTC, catarena-s commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public CommentDto createCommentToItem(@RequestHeader(value = "X-Sharer-User-Id", required = false) long userId,
Добавила проверку.

2023-05-06 17:58 UTC, catarena-s commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingDto create(
Запрет на создание бронирования одним пользователем для одной и той же вещи на пересекающиеся даты имеет смысл, если будет функционал для отмены или удаления ранее созданной брони(по ТЗ его нет, хотя статус бронирования "CANCELED" в статусы заложен).

Сделала проверку наличия подтвержденной брони(со статусом APPROVED) для вещи на пересекающиеся даты - вызываю эту проверку при создании новой  брони, и при попытке заапрувить бронь.

2023-05-06 17:58 UTC, catarena-s commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingDto approve(
Добавила проверку.

2023-05-07 11:42 UTC, z8q approved these changes

2023-05-07 11:42 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>              case CURRENT: {
На собесах могут спрашивать, как конструкции if/else и switch нарушают open-closed принцип в SOLID.
Тут
https://www.freecodecamp.org/news/open-closed-principle-solid-architecture-concept-explained/
и
тут
https://proglib.io/p/udalite-iz-koda-if-else-i-switch-case-2021-06-02
Можно посмотреть, как избегать.

Просто для информации)

2023-05-07 13:39 UTC, catarena-s commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>              case CURRENT: {
Спасибо!

2023-05-07 13:41 UTC, merged