feat: sprint 16
catarena-s/java-shareit pull request #4
Opened 2023-05-27 17:26 UTC by catarena-s

2023-05-29 19:22 UTC, z8q requested changes

2023-05-29 19:22 UTC, z8q commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          return UserMapper.toUserDto(updatedUser);
В UserDto остается валидация полей. И кое-где в контроллерах.
Например в ItemController методе create, есть проверка аргумента `@Valid @RequestBody ItemDto itemDto`
По-хорошему надо убрать
Уделить внимание вот этому пункту из тз:
`Приложение shareIt-server будет содержать всю основную логику и почти полностью повторять приложение, с которым вы работали ранее, — за исключением того, что можно будет убрать валидацию данных в контроллерах`

2023-05-30 10:44 UTC, catarena-s commented on server/src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>          return UserMapper.toUserDto(updatedUser);
Поправила

2023-05-30 20:29 UTC, z8q approved these changes

2023-05-30 20:40 UTC, merged